### ISSUE TITLE
Custom render not working for Box fixture

### ISSUE THREAD

**Issue by wycliffe-mw** [RealPeha/planck-renderer#3]
I am trying to set a custom render image for a Box fixture with the following code. The image is not drawn.

```
export function createExplorer(world) {
    const explorer = world.createDynamicBody(Vec2(0.0, 1.0));
    explorer.createFixture(planck.Box(0.89, 1.20), 1.0);

    const img = new Image();
    img.src = "images/explorer.png";
    img.onload = () => {
        explorer.render = {
            custom: (ctx, pos, size) => {
                console.log( pos.x , pos.y , size);
                ctx.drawImage(img, pos.x, pos.y, size, size);
                return true // optional
            }
        }
    };
    return explorer;
}
```

If I swap the Box for a Circle (as in the demo) it works okay.
It also doesn't work if I create a Polygon fixture.

**Comment by wycliffe-mw** [comment]
I have found the issue the size parameter has width and height for Polygon (and a Box), but is a single value for a circle. Would be good if it was more consistent. i.e. always has width and height.

**Comment by RealPeha** [comment]
in fact, this is not the only bug that exists in this library.
I know about this, but unfortunately I do not have the time and the necessary knowledge to finalize it
Therefore, I do not recommend you to use this.
If you have the opportunity, you can fork and make the necessary changes)
